version: '2'
services:

  php:
    build:
      context: ./docker/php-cli
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - .:/var/www
    ports: 
      - 8000:8000
    networks:
      - php
    depends_on: 
      - db

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks: 
      - php
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --innodb-flush-log-at-trx-commit=0

  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: db
    networks: 
      - php
    ports:
      - 8888:8080

  mail:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
    networks: 
      - php

networks: 
  php : 
    driver: bridge

volumes:
  db-data:
    driver: local